### ISSUE TITLE
Icon greyed out in menu bar

### ISSUE THREAD

**Issue by dewey** [Paszt/TMDbTools#1]
Hey,

this looks interesting. I know it's still a work in progress but I'd be interested in using it as I currently use a bunch of random user scripts that I wrote. Should it work out of the box or is there some additional step necessary to get it working in Chrome? I downloaded the repository, unpacked the zip and imported it in Chrome as an extension.

It's listed as an active extension at chrome://extensions but the icon is greyed out like this:

![screen shot 2018-03-01 at 16 06 31](https://user-images.githubusercontent.com/790262/36851847-9096d122-1d6a-11e8-84b3-2a68ffd45468.png)

Thanks in advance!

**Comment by Paszt** [comment]
The icon currently has no use so being greyed out is correct.  Right now, the only uses of the extension is to import a movie from IMDb and to update the cast of an existing movie on TMDb. I'm working on a version that adds a few more tweaks and there will be option toggles, to turn a tweak on or off, in a popup triggered by the extension icon.  

To import a movie from IMDb, the preferred way is to go to the movie page on IMDb where the extension adds a new TMDb icon to the right of the title (or possibly underneath if the title is too long). Clicking it will open a new tab where the movie is imported via a wizard with steps that include checking for duplicates. It should be pretty straight forward. You can also go to https://www.themoviedb.org/movie/new where the extension adds a textbox that allows you to input an IMDb Id and import that way.  

The other use is to update the cast list. With an existing movie on TMDb, you edit the cast and the extension adds two new button beside the existing buttons. The first is titled "COMPARE WITH IMDB" which will get the cast list from IMDb and compare it to the cast list from TMDB and present you with options to update depending on what it finds after comparing (add new cast member if not present on TMDb, update character name if different, and two other lists that just show you exact matches and cast members that are added to TMDb but not present on IMDb). The extension also checks the IMDb ids and adds it to TMDb if not already there and warns you if they are different.  The second button has a globe icon and a tooltip that says "ensure translations" which helps with checking and adding the IMDb Ids to TMDb. There's an issue with TMDb mixing secure and non-secure HTML calls if a person on TMDb doesn't have a translation added and the globe icon is a hacked way around that. It sometimes takes doing the "COMPARE WITH IMDB" twice to get all the IMDb IDs added. First click the COMPARE button and import the cast, refresh the page, click the globe icon, and COMPARE again.  

I've been meaning to do some instruction pages but haven't got to them yet. Wasn't sure if anyone else was using it.

**Comment by dewey** [comment]
Ah okay, thanks for the explanation. Will give it a try and report back!
