### ISSUE TITLE
TV Special / TV movie doesn't have the button

### ISSUE THREAD

**Issue by dewey** [Paszt/TMDbTools#3]
I think as this is a standalone TV movie it should be able to be imported as a movie to TMDB, the button doesn't show up for it. Is it maybe excluded because it has "TV" in the object type?

https://www.imdb.com/title/tt6054328/?ref_=fn_al_tt_2

**Comment by Paszt** [comment]
I've fixed this locally a while ago, but I'm hesitant to continue sharing this extension. A brief look at your recent activity on TMDb shows you are importing concatenated overviews. You should really review the information you're importing and be sure it conforms to TMDb's guidelines. For one example see here: https://www.themoviedb.org/movie/573472-one-halloween

**Comment by Paszt** [comment]
As I said, that was just one example. There were several others just in your first page of activity.
